### ISSUE TITLE
Running example-classic.test.js directly results in "TypeError: page._client.send is not a function"

### ISSUE THREAD

**Issue by shivladsky** [applitools/tutorial-puppeteer#1]
I first got this error "TypeError: page._client.send is not a function" when following the "Get Started" guide for Applitools, thought I did something wrong. But then I thought I'll copy-paste example code from **example-classic.test.js** and run it as is - got the same error.

Is this due to the latest version of Puppeteer not supporting something? Using Puppeteer 15.3.2

**Comment by shivladsky** [comment]
Confirming this is a compatibility issue with the latest Puppeteer. Works with 11.0.0 (used in this repo), but not latest (15.3.2 and 15.4.0). Only the Ultrafast Grid script still works.
